# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import reply_pb2 as reply__pb2
from proto import request_pb2 as request__pb2


class KolombiaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendMessage = channel.unary_unary(
        '/Kolombia/sendMessage',
        request_serializer=request__pb2.Request.SerializeToString,
        response_deserializer=reply__pb2.Reply.FromString,
        )
    self.ListNews = channel.unary_stream(
        '/Kolombia/ListNews',
        request_serializer=request__pb2.Request.SerializeToString,
        response_deserializer=reply__pb2.Reply.FromString,
        )
    self.ListMessages = channel.stream_unary(
        '/Kolombia/ListMessages',
        request_serializer=request__pb2.Request.SerializeToString,
        response_deserializer=reply__pb2.Reply.FromString,
        )


class KolombiaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListNews(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListMessages(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KolombiaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=request__pb2.Request.FromString,
          response_serializer=reply__pb2.Reply.SerializeToString,
      ),
      'ListNews': grpc.unary_stream_rpc_method_handler(
          servicer.ListNews,
          request_deserializer=request__pb2.Request.FromString,
          response_serializer=reply__pb2.Reply.SerializeToString,
      ),
      'ListMessages': grpc.stream_unary_rpc_method_handler(
          servicer.ListMessages,
          request_deserializer=request__pb2.Request.FromString,
          response_serializer=reply__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Kolombia', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
